# This is a basic workflow to help you get started with Actions

name: USAJobsData

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:  
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: API Call
        run: |
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=NV;AF;AR&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o NV-AF-AR-Count.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD01;DD02;DD04;DD05;DD06;DD07;DD08;DD10;DD11;DD12;DD13;DD15;DD16;DD21;DD23;DD25;DD26;DD27;DD28;DD29;DD34;DD35;DD36;DD48;DD58;DD59;DD60;DD61;DD62;DD63;DD64;DD65;DD66;DD69&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o DD-1-Count.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD70;DD71;DD72;DD73;DD74;DD68;DD75;DD77;DD78;DD79;DD80;DD67;DD76;DD81;DD53;DD82;DD84;DD83;DD00&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o DD-2-Count.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD;NV;AF;AR&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o usajobsdata-all.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD;NV&Fields=min&SortField=location&SortDirection=Asc&ResultsPerPage=9000' -o usajobs_Count_DD_NV.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=AF&Fields=min&SortField=location&SortDirection=Asc&ResultsPerPage=9000' -o usajobs_Count_AF.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=AR&Fields=min&SortField=location&SortDirection=Asc&ResultsPerPage=9000' -o usajobs_Count_AR.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD;NV&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=9000' -o usajobsdata.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=AF&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=9000' -o usajobsdata-2.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=AR&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=9000' -o usajobsdata-3.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?JobCategoryCode=0180;0181;0185;0186;0187;0101;0102;0638;0685&Organization=DD;NV;AR;AF&SortField=location&SortDirection=Asc&ResultsPerPage=9000' -o usajobs_Health_Social_sciences.json
          git config --global user.name "GitHub Action"
          git config --global user.email "devstoneapps@gmail.com"
          git add NV-AF-AR-Count.json
          git add DD-1-Count.json
          git add DD-2-Count.json
          git add usajobsdata-all.json
          git add usajobs_Count_DD_NV.json
          git add usajobs_Count_AF.json
          git add usajobs_Count_AR.json
          git add usajobsdata.json
          git add usajobsdata-2.json
          git add usajobsdata-3.json
          git add usajobs_Health_Social_sciences.json
          git commit -m "USA Jobs API fetching"
          git push
        env:
          SECRETKEY: ${{ secrets.AUTH_KEY }}
          SECRETAGENT: ${{ secrets.USER_AGENT }}

      - name: Modify JSON file
        run: |
          echo "const fs = require('fs');" > modify-json.js
          echo "const filePath = 'usajobsdata.json';" >> modify-json.js
          echo "const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));" >> modify-json.js
          echo "data.SearchResult.SearchResultItems.forEach(item => {" >> modify-json.js
          echo "    delete item.MatchedObjectDescriptor.OrganizationName;" >> modify-json.js
          echo "});" >> modify-json.js
          echo "fs.writeFileSync(filePath, JSON.stringify(data, null, 2));" >> modify-json.js

          # Run the Node.js script
          node modify-json.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "devstoneapps@gmail.com"
          git add usajobsdata.json
          git commit -m "Remove QualificationSummary from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
