# This is a basic workflow to help you get started with Actions

name: USAJobsData

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:  
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: API Call
        run: |
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=NV;AF;AR&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o NV-AF-AR-Count.json
          curl -H "Host: data.usajobs.gov" -H "User-Agent: $SECRETAGENT" -H "Authorization-Key: $SECRETKEY" -H "Accept: application/json" 'https://data.usajobs.gov/api/search?Organization=DD01;DD02;DD04;DD05;DD06;DD07;DD08;DD10;DD11;DD12;DD13;DD15;DD16;DD21;DD23;DD25;DD26;DD27;DD28;DD29;DD34;DD35;DD36;DD48;DD58;DD59;DD60;DD61;DD62;DD63;DD64;DD65;DD66;DD69&Fields=min&SortField=location&RemoteIndicator=False&SortDirection=Asc&ResultsPerPage=1' -o DD-1-Count.json
          # Add additional curl commands as needed...
          git config --global user.name "GitHub Action"
          git config --global user.email "devstoneapps@gmail.com"
          git add NV-AF-AR-Count.json DD-1-Count.json # Add other files as needed...
          git commit -m "USA Jobs API fetching"
          git push
        env:
          SECRETKEY: ${{ secrets.AUTH_KEY }}
          SECRETAGENT: ${{ secrets.USER_AGENT }}

      - name: Modify JSON file
        run: |
          const fs = require('fs');
          const filePath = 'usajobsdata.json';

          // Read the JSON file
          const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

          // Remove the QualificationSummary object if it exists
          if (data.QualificationSummary) {
              delete data.QualificationSummary;
          }

          // Write the updated JSON back to the file
          fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "devstoneapps@gmail.com"
          git add usajobsdata.json
          git commit -m "Remove QualificationSummary from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

